#include "Tools.hpp"

#include "Diagnostics.hpp"
#include "Embedded.hpp"
#include "Lexer.hpp"
#include "Parser.hpp"

#include <filesystem>
#include <format>
#include <fstream>



namespace Noether
{

namespace
{
    std::string mdCell(std::string s)
    {
        std::string out;
        for (const char c : s) out += c == '|' ? std::string("\\|") : std::string(1, c);
        return out;
    }

    // The version-matched reference: built from the same tables as the lexer and the compiler.
    std::string referenceText()
    {
        std::string md = std::format("# Noether {} reference (language {})\n\nGenerated by `noether skill --full`; it describes the "
                                     "installed binary.\n\n",
                                     kVersion, kLangVersion);
        md += "## Gates\n\n| Gate | Slots | Params | Clifford | Meaning |\n|---|---|---|---|---|\n";
#define NTR_GATE(name, roles, params, clifford, meaning)                                                                   \
    md += std::format("| `{}` | {} | {} | {} | {} |\n", name, mdCell(std::string(roles) == "1" ? "1" : std::string(roles) == "c>t" ? "c→t" \
                      : std::string(roles) == "c,c>t" ? "c,c→t" : std::string(roles) == "c>a,b" ? "c→a,b" : roles), params,        \
                      mdCell(clifford), mdCell(meaning));
#include "tokens.def"
        md += "\nAliases: ";
#define NTR_GATE_ALIAS(alias, canonical, dagger) md += std::format("`{}` → `{}{}`, ", alias, canonical, (dagger) ? "†" : "");
#include "tokens.def"
        md += "rewritten by the formatter.\n\n## Functions\n\n| Function | Meaning |\n|---|---|\n";
#define NTR_FUNC(name, meaning) md += std::format("| `{}` | {} |\n", name, mdCell(meaning));
#include "tokens.def"
        md += "\n## Channels\n\n| Channel | Qubits | Params | Pauli (both backends) | Meaning |\n|---|---|---|---|---|\n";
#define NTR_CHANNEL(name, arity, params, pauli, meaning)                                                                    \
    md += std::format("| `{}` | {} | {} | {} | {} |\n", name, (arity) == 0 ? std::string("k") : std::to_string(arity), params, \
                      (pauli) ? "yes" : "no", mdCell(meaning));
#include "tokens.def"
        md += "\n## Keywords\n\n";
#define NTR_KEYWORD(Name, text) md += std::format("`{}` ", text);
#include "tokens.def"
        md += "\n\n## Tokens: canonical, LaTeX, ASCII\n\nType any column; the formatter writes the canonical one. LaTeX "
              "commands take one backslash.\n\n| Canonical | LaTeX | ASCII input | ASCII canonical | Meaning |\n|---|---|---|---|---|\n";
        for (const AliasRow& r : aliasTable())
            md += std::format("| {} | {} | {} | {} | {} |\n", mdCell(r.canonical), mdCell(r.latex), mdCell(r.ascii), mdCell(r.asciiCanonical),
                              mdCell(r.meaning));
        md += "\n## Diagnostic codes\n\nRun `noether explain CODE` for a wrong and a right example.\n\n| Code | Meaning |\n|---|---|\n";
        for (const CodeInfo& c : codeCatalog()) md += std::format("| {} | {} |\n", c.code, mdCell(std::string(c.title)));
        md += "\n## Exit codes\n\n0 ok · 1 compile errors · 2 usage or I/O error · 3 assertion failed · 4 resource limit or timeout · "
              "5 internal error · 6 research integrity failure (E8001)\n";
        md += "\n## Grammar (EBNF)\n\n```ebnf\n" + std::string(grammarText()) + "```\n";
        return md;
    }

    std::string_view embedded(std::string_view path)
    {
        for (const EmbeddedFile& f : embeddedSkills())
            if (f.path == path) return f.text;
        return {};
    }
} // namespace

std::string skillText(bool full)
{
    std::string s(embedded("qsm/SKILL.md"));
    if (full) s += "\n\n" + referenceText();
    return s;
}

std::size_t installSkills(const std::string& dir, std::string& error)
{
    namespace fs = std::filesystem;
    std::size_t n = 0;
    auto write = [&](const fs::path& p, std::string_view text)
    {
        std::error_code ec;
        fs::create_directories(p.parent_path(), ec);
        std::ofstream o(p, std::ios::binary | std::ios::trunc);
        o << text;
        if (!o)
        {
            error = std::format("cannot write {}", p.string());
            return false;
        }
        ++n;
        return true;
    };
    for (const EmbeddedFile& f : embeddedSkills())
        if (!write(fs::path(dir) / f.path, f.text)) return n;
    write(fs::path(dir) / "qsm" / "reference.md", referenceText());
    return n;
}

} // namespace Noether
