// Gate-level agreement with the source frameworks. fixtures/gates.json holds reference unitaries
// generated by Qiskit, Cirq and Stim (fixtures/generate.py); each entry is imported and its unitary
// rebuilt on the state vector. Comparisons are up to global phase, which no measurement can see:
// a wrong phase under a control is a relative phase, and the comparison of the whole controlled
// matrix catches it. The embedded include files are checked against their own definitions.

#include "InteropTestUtil.hpp"

#include "interop/Qasm.hpp"
#include "interop/Stim.hpp"

#include <set>

using namespace InteropTest;
using Noether::Json;

namespace
{

constexpr double kTol = 1e-10;

const Json& fixtures()
{
    static const Json doc = []
    {
        const std::string text = NoetherTest::readText(kInteropDir / "fixtures" / "gates.json");
        auto j = Json::parse(text);
        if (!j) throw std::runtime_error("cannot parse fixtures/gates.json");
        return *j;
    }();
    return doc;
}

const Json::Array& entries(std::string_view framework)
{
    const Json* a = fixtures().find(framework);
    if (!a) throw std::runtime_error(std::format("fixtures/gates.json has no `{}` entries", framework));
    return a->asArray();
}

std::vector<double> randomAngles(std::size_t k, std::mt19937_64& rng)
{
    std::uniform_real_distribution<double> u(-3.1, 3.1);
    std::vector<double> out(k);
    for (double& x : out) x = u(rng);
    return out;
}

// Single-qubit gates as matrices, for the include-file checks.
Eigen::Matrix2cd u3(double t, double p, double l)
{
    const cd i(0, 1);
    Eigen::Matrix2cd m;
    m << std::cos(t / 2), -std::exp(i * l) * std::sin(t / 2), std::exp(i * p) * std::sin(t / 2), std::exp(i * (p + l)) * std::cos(t / 2);
    return m;
}

// Control on qubit 0, target qubit 1, in core order (index bit q = qubit q).
Eigen::Matrix4cd controlledOn0(const Eigen::Matrix2cd& u)
{
    Eigen::Matrix4cd m = Eigen::Matrix4cd::Identity();
    // Indices with qubit 0 set: 1 (q1 = 0) and 3 (q1 = 1).
    m(1, 1) = u(0, 0);
    m(1, 3) = u(0, 1);
    m(3, 1) = u(1, 0);
    m(3, 3) = u(1, 1);
    return m;
}

} // namespace

TEST(InteropGates, StimUnitariesMatchStim)
{
    std::size_t checked = 0;
    for (const Json& e : entries("stim"))
    {
        const std::string text = e.find("text")->asString();
        SCOPED_TRACE(text);
        const ImportResult r = load("gate.stim", text + "\n", "stim");
        if (!r.circuit) continue;
        const auto n = static_cast<std::size_t>(e.find("qubits")->asInt());
        ASSERT_EQ(r.circuit->numQubits, n);
        EXPECT_LE(maxDiffUpToPhase(unitaryOf(*r.circuit), matrixFromJson(*e.find("matrix"))), kTol);
        ++checked;
    }
    EXPECT_GT(checked, 80U);
}

TEST(InteropGates, EveryStimUnitaryGateIsCovered)
{
    std::set<std::string> covered;
    for (const Json& e : entries("stim"))
    {
        const std::string text = e.find("text")->asString();
        covered.insert(text.substr(0, text.find(' ')));
    }
    // Every name the generator found unitary must be accepted by the importer.
    const auto names = stimGateNames();
    for (const std::string& name : covered)
        EXPECT_NE(std::ranges::find(names, std::string_view(name)), names.end()) << name;
}

TEST(InteropGates, QiskitCircuitJsonMatchesOperator)
{
    for (const Json& e : entries("qiskit"))
    {
        const std::string name = e.find("name")->asString();
        SCOPED_TRACE("qiskit " + name);
        const ImportResult r = load(name + ".json", e.find("circuit")->dump(-1), "circuit");
        if (!r.circuit) continue;
        EXPECT_LE(maxDiffUpToPhase(unitaryOf(*r.circuit), matrixFromJson(*e.find("matrix"))), kTol);
    }
}

TEST(InteropGates, QiskitQasmDumpsMatchOperator)
{
    std::size_t checked = 0;
    for (const Json& e : entries("qiskit"))
        for (const char* key : {"qasm2", "qasm3"})
        {
            const Json* text = e.find(key);
            if (!text) continue;
            const std::string name = e.find("name")->asString();
            SCOPED_TRACE(std::format("qiskit {} via {}\n{}", name, key, text->asString()));
            const ImportResult r = load(name + ".qasm", text->asString(), key);
            if (!r.circuit) continue;
            EXPECT_LE(maxDiffUpToPhase(unitaryOf(*r.circuit), matrixFromJson(*e.find("matrix"))), kTol);
            ++checked;
        }
    EXPECT_GT(checked, 80U);
}

TEST(InteropGates, CirqCircuitJsonMatchesUnitary)
{
    for (const Json& e : entries("cirq"))
    {
        const std::string name = e.find("name")->asString();
        SCOPED_TRACE("cirq " + name);
        const ImportResult r = load("cirq.json", e.find("circuit")->dump(-1), "circuit");
        if (!r.circuit) continue;
        EXPECT_LE(maxDiffUpToPhase(unitaryOf(*r.circuit), matrixFromJson(*e.find("matrix"))), kTol);
    }
}

// stdgates.inc is exact under the OpenQASM 3 U = e^{iθ/2}·u3 convention, so its fast paths must
// equal the definitions with phase. The one exception is `CX`, defined as ctrl @ U(π, 0, π), which
// is controlled-(iX); the importer runs it as the CNOT every producer means by it.
TEST(InteropGates, StdgatesFastPathsEqualDefinitions)
{
    std::mt19937_64 rng(11);
    std::size_t natives = 0;
    for (const std::string& g : qasmIncludeGates("stdgates.inc"))
    {
        SCOPED_TRACE("stdgates.inc " + g);
        const auto shape = qasmGateShape("stdgates.inc", g);
        ASSERT_TRUE(shape);
        for (int trial = 0; trial < 3; ++trial)
        {
            const auto params = randomAngles(shape->params, rng);
            const Eigen::MatrixXcd def = qasmGateMatrix("stdgates.inc", g, params, false);
            ASSERT_EQ(def.rows(), Eigen::Index{1} << shape->qubits);
            if (!shape->native) continue;
            const Eigen::MatrixXcd fast = qasmGateMatrix("stdgates.inc", g, params, true);
            if (g == "CX")
            {
                const cd i(0, 1);
                Eigen::Matrix2cd x;
                x << 0, 1, 1, 0;
                EXPECT_LE(maxDiff(def, controlledOn0(i * x)), kTol);
                EXPECT_LE(maxDiff(fast, controlledOn0(x)), kTol);
            }
            else EXPECT_LE(maxDiff(fast, def), kTol);
            natives += trial == 0;
        }
    }
    EXPECT_GT(natives, 20U);
}

// OpenQASM 2 gives U no phase, so qelib1.inc definitions fix each gate only up to global phase.
TEST(InteropGates, Qelib1FastPathsEqualDefinitionsUpToPhase)
{
    std::mt19937_64 rng(12);
    std::size_t natives = 0;
    for (const std::string& g : qasmIncludeGates("qelib1.inc"))
    {
        SCOPED_TRACE("qelib1.inc " + g);
        const auto shape = qasmGateShape("qelib1.inc", g);
        ASSERT_TRUE(shape);
        for (int trial = 0; trial < 3; ++trial)
        {
            const auto params = randomAngles(shape->params, rng);
            const Eigen::MatrixXcd def = qasmGateMatrix("qelib1.inc", g, params, false);
            ASSERT_EQ(def.rows(), Eigen::Index{1} << shape->qubits);
            if (!shape->native) continue;
            EXPECT_LE(maxDiffUpToPhase(qasmGateMatrix("qelib1.inc", g, params, true), def), kTol);
            natives += trial == 0;
        }
    }
    EXPECT_GT(natives, 20U);
}

TEST(InteropGates, Qasm3UCarriesItsPhaseUnderControl)
{
    // ctrl @ U(θ, φ, λ) = controlled(e^{iθ/2}·u3(θ, φ, λ)), so the phase becomes a relative phase.
    const double t = 0.7, p = -0.4, l = 1.9;
    const ImportResult r = load("u.qasm", std::format("OPENQASM 3.0;\nqubit[2] q;\nctrl @ U({}, {}, {}) q[0], q[1];\n", t, p, l));
    ASSERT_TRUE(r.circuit);
    const cd i(0, 1);
    EXPECT_LE(maxDiff(unitaryOf(*r.circuit), controlledOn0(std::exp(i * t / 2.0) * u3(t, p, l))), kTol);
}

TEST(InteropGates, Qasm2UIsU3)
{
    const double t = 0.7, p = -0.4, l = 1.9;
    const ImportResult r = load("u.qasm", std::format("OPENQASM 2.0;\nqreg q[1];\nU({}, {}, {}) q[0];\n", t, p, l));
    ASSERT_TRUE(r.circuit);
    EXPECT_LE(maxDiffUpToPhase(unitaryOf(*r.circuit), u3(t, p, l)), kTol);
}
